name: Cypress + Cucumber testing

on:
  workflow_dispatch: 
  push:
    branches:
      - main 

jobs:
  cypress_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Crate reports folder
        run: mkdir cypress/reports

      - name: Run Cypress tests 
        run: npm run cypress:run
        id: runCypressTest
        continue-on-error: true

      - name: Generate json
        run: npm run report:generate:json
        
      - name: Generate report
        run: npm run report:generate:html
        
      - name: Set up GitHub Pages 
        if: ${{ steps.runCypressTest.outcome == 'success' || steps.runCypressTest.outcome == 'failure'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/cucumber-report.html
          publish_branch: cypress-cucumber-report
